### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by Jylhis** [Jylhis/Lappbill#3]

**Comment by sonwani237** [comment]
Hello  everyone,
I an getting encrypted data from api how to decrypt it.
Encrypted Data-
p1SvSCiAxupKrrZXzjXQk48EeA7F1jnGymvqGlmAOMOrnUVZpopohJ8WYp/DI3nUuc4wG57FQWi2
TfwS+H7VSsanfbhKGf+i6H1iQchaSi9lgjxv96JCyhM9WaF7T9UuL5efwgwslGqGG54Ctx6Ykg==

It's decryption-
{
  "status": {
    "status": "500",
    "message": "Your request could not be served by the system. Please try again!"
  }
}

Thanks in advance Please solve it
